############################################# Ceritificate Replica Set
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mdb-rs-server-tls
  namespace: mongodb-operator
spec:
  secretName: certs-mdb-rs-cert    ###### Secret 
  issuerRef:
    name: my-ca-issuer
    kind: ClusterIssuer
  duration: 240h0m0s
  renewBefore: 120h0m0s
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  dnsNames:
    # per‑member pod + pod FQDNs (3‑member RS)
    - "replica-set-0"
    - "replica-set-0.replica-set-svc.mongodb-operator.svc.cluster.local"
    - "replica-set-1"
    - "replica-set-1.replica-set-svc.mongodb-operator.svc.cluster.local"
    - "replica-set-2"
    - "replica-set-2.replica-set-svc.mongodb-operator.svc.cluster.local"
    # service‑level FQDNs
    - "replica-set-svc.mongodb-operator.svc.cluster.local"
    - "*.replica-set-svc.mongodb-operator.svc.cluster.local"

---

############################################# Ceritificate Search
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mdb-rs-search-tls
  namespace: mongodb-operator
spec:
  secretName: mdb-rs-search-tls    ###### Secret 
  issuerRef:
    name: my-ca-issuer
    kind: ClusterIssuer
  duration: 240h0m0s
  renewBefore: 120h0m0s
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  dnsNames:
    - "replica-set-search-svc.mongodb-operator.svc.cluster.local"

---

############################################# Ceritificate Search
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: om-http-cert
  namespace: mongodb-operator
spec:
  secretName: om-http-cert   ###### Secret
  issuerRef:
    name: my-ca-issuer
    kind: ClusterIssuer
  duration: 240h0m0s
  renewBefore: 120h0m0s
  usages:
    - digital signature
    - key encipherment
    - server auth
  dnsNames:
    - "ops-manager-svc.mongodb-operator.svc.cluster.local"