apiVersion: mongodb.com/v1
kind: MongoDBSearch
metadata:
  name: replica-set # same name as the MongoDB replica-set resource to avoid specifying source.mongodbResourceRef
  namespace: mongodb-operator
spec:
  resourceRequirements:
    limits:
      cpu: "3"
      memory: 5Gi
    requests:
      cpu: "2"
      memory: 3Gi