---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: replica-set
  namespace: mongodb-operator
spec:
  members: 3
  version: "8.0.7"
  opsManager:
    configMapRef:
           # Must match metadata.name in ConfigMap file
      name: my-project
  credentials: organization-secret
  type: ReplicaSet
  persistent: true
...
