apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager
  namespace: mongodb-operator
spec:
  version: "8.0.16"
  adminCredentials: om-admin-secret
  externalConnectivity:
    type: LoadBalancer
  configuration:
    mms.ignoreInitialUiSetup: "true"
    automation.versions.source: remote
    mms.adminEmailAddr: support@example.com
    mms.fromEmailAddr: support@example.com
    mms.replyToEmailAddr: support@example.com
    mms.mail.hostname: example.com
    mms.mail.port: "465"
    mms.mail.ssl: "false"
    mms.mail.transport: smtp
  applicationDatabase:
    members: 3
    version: "8.2.0"

---

apiVersion: v1
kind: Secret
metadata:
  name: om-admin-secret
  namespace: mongodb-operator
type: Opaque
stringData:
  Username: "my-user"
  Password: "123456"
  FirstName: ""
  LastName: ""
