apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager
  namespace: mongodb-operator
spec:
  version: "8.0.22"
  adminCredentials: om-admin-secret
  externalConnectivity:
    type: LoadBalancer
  configuration:
    mms.ignoreInitialUiSetup: "true"
    automation.versions.source: remote
    mms.adminEmailAddr: support@example.com
    mms.fromEmailAddr: support@example.com
    mms.replyToEmailAddr: support@example.com
    mms.mail.hostname: example.com
    mms.mail.port: "466"
    mms.mail.ssl: "false"
    mms.mail.transport: smtp
  applicationDatabase:
    members: 3
    version: "8.2.0"

---

# This is a Global Owner User used basically only for the initial setup of Ops Manager.
# It is not recommended to use this user for daily operations
# For deploying MongoDB resources, an API Key needs to be created in OM UI (e.g. replica-set/secret.yaml)
apiVersion: v1
kind: Secret
metadata:
  name: om-admin-secret
  namespace: mongodb-operator
type: Opaque
stringData:
  Username: "om-admin"
  Password: "ldsflkh@#!@asd42" # strong password needed or OM will not start monitoring for AppDB
  FirstName: "Administrator" # cannot be empty or MCK will not be able to create
  LastName: "Ops Manager"  # cannot be empty or MCK will not be able to create
