---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: replica-set
  namespace: mongodb-operator
spec:
  type: ReplicaSet
  members: 3
  version: "8.2.0-ent"
  persistent: true
  # OpsManager Config
  opsManager:
    configMapRef:
      name: my-project
  credentials: organization-secret
  # Disable authentication to be able to manage the database without credentials
  # do not do this in production environments
  security:
    authentication:
      enabled: false